apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "16k"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "16k"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "16k"
    nginx.ingress.kubernetes.io/client-header-timeout: "120s"
    nginx.ingress.kubernetes.io/client-body-timeout: "120s"
    cert-manager.io/cluster-issuer: homelab-ca
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - $REPLACE #HA Domain
      secretName: ha-tls
  rules:
    - host: $REPLACE #HA Domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
